Speciality model
Arturgouveia1970/doctor-appointment-back-end pull request #12
Opened 2022-10-10 13:38 UTC by principles31

# The following were implemented in this **PR** as the project requirements: 
> Create Speciality model
> Set validations
> Define associations
> has many doctor's

2022-10-10 15:25 UTC, Arturgouveia1970 commented on app/models/speciality.rb
> +end
Kindly add the doctor's foreign key to the speciality table.

2022-10-10 15:29 UTC, Arturgouveia1970 requested changes
Hello @principles31, you have done a great job creating the specialities model and controller, however, I believe that you need to make a couple of changes:

2022-10-10 15:29 UTC, Arturgouveia1970 commented on db/migrate/20221010922901_create_specialists.rb
> +        t.integer :rating, comment: 'Specialists Doctor rating system', limit: 1
Kindly remove the rating as you cannot rate a doctor's specialy.

2022-10-11 10:20 UTC, principles31 commented
- [x] Kindly add the doctor's foreign key to the speciality table.
- [x] Kindly remove the rating as you cannot rate a doctor's specialy.
- [x] The above changes requested by the reviewer have been implemented.

2022-10-11 10:28 UTC, Arturgouveia1970 approved these changes
Hello @principles31, Job well done, I can see that you have implemented all changes required by the last reviewer and that a speciality can be created. Congratulations, it's time to merge.

2022-10-11 10:28 UTC, merged